[build]
  publish = "public"
  command = "git submodule update --init --recursive && gatsby build"
[build.environment]
  YARN_VERSION = "1.15.0"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_OPTIONS = "--max_old_space_size=8192"